language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update    
install:
  - composer install --dev --prefer-source

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
